server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: acopio-service
          uri: lb://acopio-service
          predicates:
            - Path=/acopio/**
        - id: laboratorio-service
          uri: lb://laboratorio-service
          predicates:
            - Path=/laboratorio/**
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: quincena-service
          uri: lb://quincena-service
          predicates:
            - Path=/quincena/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**