apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: database
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: password
            - name: POSTGRES_DB_PROVEEDOR
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-proveedor
                  key: name
            - name: POSTGRES_DB_ACOPIO
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-acopio
                  key: name
            - name: POSTGRES_DB_LABORATORIO
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-laboratorio
                  key: name
            - name: POSTGRES_DB_PLANILLA
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-planilla
                  key: name
            - name: POSTGRES_DB_QUINCENA
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap-quincena
                  key: name
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-storage
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim