apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedor-service
  template:
    metadata:
      labels:
        app: proveedor-service
    spec:
      containers:
        - name: proveedor-service
          image: hfaravenak/proveedor-service-mingeso2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://proveedor-db-service:5432/proveedor_db
            - name: SPRING_DATASOURCE_USERNAME
              value: username
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/